spring.application.name=analytics-service

server.port=8083

# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://postgres:5432/api_monetization
spring.datasource.username=postgres
spring.datasource.password=Nani123@
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Eureka
# ===============================
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

# ===============================
# Swagger
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true